class AMF0Marker:
    number = b'\x00'
    boolean = b'\x01'
    string = b'\x02'
    object = b'\x03'
    movieclip = b'\x04'
    null = b'\x05'
    undefined = b'\x06'
    reference = b'\x07'
    ecma_array = b'\x08'
    object_end = b'\x09'
    strict_array = b'\x0A'
    date = b'\x0B'
    long_string = b'\x0C'
    unsupported = b'\x0D'
    recordset = b'\x0E'
    xml_document = b'\x0F'
    typed_object = b'\x10'
